[toolchain]
package_manager = "yarn"

[features]
resolution = false
skip-lint = false

[programs.devnet]
dark_souls_vrf = "3yFrLcHmwCpNjeSR4sFNVd1K3BTzwVc3Nz13ToeHnRfs"

[programs.localnet]
dark_souls_vrf = "3yFrLcHmwCpNjeSR4sFNVd1K3BTzwVc3Nz13ToeHnRfs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -r ts-node/register -t 10000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
